services:
  # server:
  #   build:
  #     context: .
  #     target: dev
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

volumes:
  mongo-db:
