services:
  # server:
  #   build:
  #     context: ./server
  #     target: dev
  #   volumes:
  #     - ./server:/app
  #     - /app/node_modules
  #   ports:
  #     - "1337:1337"

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db
    ports:
      - "27017:27017"

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"

volumes:
  mongo-db:
